import { type NextPage } from "next";
import * as fs from "fs";
import path from "path";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import Main from "~/components/home";

interface HomeProps {
  pages: { name: string; path: string }[];
}

const Home: NextPage<HomeProps> = (props) => {
  const { pages } = props;
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main pages={pages} />
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};

export async function getServerSideProps(context: any) {
  const pages = fs.readdirSync(path.join("src", "pages/designs"));
  const newPages = pages.map((page) => {
    const name = page.replace(".tsx", "");
    return {
      name,
      path: "/designs/" + name,
    };
  });
  return {
    props: {
      pages: newPages,
    },
  };
}
