import { type NextPage } from "next";
import * as fs from "fs";
import path from "path";
import Head from "next/head";

import Main from "~/components/home";

interface HomeProps {
  pages: { name: string; path: string }[];
}

const Home: NextPage<HomeProps> = (props) => {
  const { pages } = props;
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main pages={pages} />
    </>
  );
};

export default Home;

export function getServerSideProps() {
  const pages = fs.readdirSync(path.join("src", "pages/designs"));
  const newPages = pages.map((page) => {
    const name = page.replace(".tsx", "");
    return {
      name,
      path: "/designs/" + name,
    };
  });
  return {
    props: {
      pages: newPages,
    },
  };
}
